name: Build AAR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build AAR
      run: |
        gradle assembleRelease

    - name: Upload AAR
      uses: actions/upload-artifact@v3
      with:
        name: aar-output
        path: '**/*.aar'
