name: Build V2Ray AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Build AAR
        run: |
          gomobile bind -target=android ./v2ray
          mkdir -p output
          mv *.aar output/

      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: v2ray-aar
          path: output/*.aar
